job_parser_task:
  description: >
    Analyze the job posting URL provided {job_listing}
    to extract key skills, experiences, and qualifications
    required. Use the tools to gather content and identify 
    and categorize the requirements.
  expected_output: >
    A structured list of job requirements, including necessary skills,
    qualifications, and experiences
  agent: job_parser 

resume_parser_task:
  description: >
    Parse the most relevant information in raw_resume for {job_listing}. Make sure
    the experience is in Action-Context-Result format. Do not make up anything about
    ths user.
  expected_output: >
    A profile document that highlights the user's qualifications for the {job_listing}
  agent: resume_reader
  context: 
    - job_parser_task

resume_editor_task:
  description: >
    Format the user's information into an Applicant-Tracking-Systems optimized resume.
    Do not make up anything about the user.
  expected_output: >
    A perfectly formatted Resume with all the user's critical information
  agent: resume_writer
  context:
    - resume_parser_task
  output_file: output/resume.md


